server:
  port: 8885
  servlet:
    context-path: /webapi
spring:
  application:
    name: webapi
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8887/eureka/
  instance:
    prefer-ip-address: true
