server:
  port: 8885
  servlet:
    context-path: /webapi
spring:
  application:
    name: webapi
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 300
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        acknowledge-mode: manual
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8887/eureka/
  instance:
    prefer-ip-address: true
router:
  url: http://ROUTER/service
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
